apiVersion: apps/v1
kind: Deployment
metadata:
  name: cvapi-deployment
  labels:
    app: cvapi-server
spec:
  selector:
    matchLabels:
      app: cvapi-server
  replicas: 1
  template:
    metadata:
      labels:
        app: cvapi-server
    spec:
      containers:
      - name: cvapi-container
        image: docker.io/irvingrcm123/apicv:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cvapi-server
  name: cvapi-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: cvapi-server
  type: LoadBalancer
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cvapi-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cvapi-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50